import {readFileSync,existsSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
async function loadPure(file){const source=readFileSync(file,'utf8');const {outputText}=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}});return import('data:text/javascript;base64,'+Buffer.from(outputText).toString('base64'))}
const {properties,defaultFilters,filterProperties,validateFilters}=await loadPure('lib/properties.ts');
const {validateContact}=await loadPure('lib/request-validation.ts');
let checks=0;const check=(name,run)=>{run();checks++;console.log('PASS '+name)};
check('Catálogo sem IDs duplicados',()=>assert.equal(new Set(properties.map(p=>p.id)).size,9));
check('Filtros por categoria e finalidade',()=>{for(const type of ['casa','predio','galpao']){assert.equal(filterProperties({...defaultFilters,type}).length,3);for(const purpose of ['comprar','alugar'])assert.ok(filterProperties({...defaultFilters,type,purpose}).every(p=>p.type===type&&p.purpose===purpose))}assert.equal(filterProperties({...defaultFilters,type:'casa',purpose:'alugar'}).length,1)});
check('Busca ignora acentos e aceita código',()=>{assert.equal(filterProperties({...defaultFilters,q:'parnaiba'}).length,2);assert.equal(filterProperties({...defaultFilters,q:'ti-101'})[0].id,'TI-101');assert.equal(filterProperties({...defaultFilters,q:'GALPAO'}).length,3)});
check('Preço e área aplicados juntos',()=>{const rows=filterProperties({...defaultFilters,purpose:'alugar',budget:'30000',area:'500'});assert.equal(rows.length,2);assert.ok(rows.every(p=>p.price<=30000&&p.area>=500))});
check('Ordenação não altera o catálogo original',()=>{const before=properties.map(p=>p.id);const sorted=filterProperties({...defaultFilters,sort:'menor'});assert.equal(sorted[0].id,'TI-102');assert.deepEqual(properties.map(p=>p.id),before);const area=filterProperties({...defaultFilters,sort:'area'});assert.equal(area[0].id,'TI-301')});
check('Estado vazio e parâmetros inválidos',()=>{assert.equal(filterProperties({...defaultFilters,q:'nenhum resultado xyz'}).length,0);assert.deepEqual(validateFilters({type:'script',budget:'-50',city:['Osasco'],sort:'inválido'}),defaultFilters);assert.equal(validateFilters({q:'x'.repeat(200)}).q.length,120)});
const valid={name:'Pessoa de Teste',phone:'',email:'teste@example.com',purpose:'comprar',type:'casa',message:'Procuro uma casa com quintal.'};
check('Contato válido aceita só e-mail ou só telefone',()=>{assert.deepEqual(validateContact(valid),{});assert.deepEqual(validateContact({...valid,email:'',phone:'(11) 99999-1234'}),{});assert.deepEqual(validateContact({...valid,email:'',phone:'+55 (11) 99999-1234'}),{})});
check('Contato rejeita campos vazios e endereços inválidos',()=>{const empty=validateContact({...valid,name:' ',phone:'',email:'',message:'curto'});assert.ok(empty.name&&empty.phone&&empty.email&&empty.message);assert.ok(validateContact({...valid,email:'sem-arroba'}).email);assert.ok(validateContact({...valid,phone:'123'}).phone)});
check('Todas as imagens locais e variações existem',()=>{for(const p of properties){assert.ok(existsSync(`public/images/${p.image}.webp`));assert.ok(existsSync(`public/images/${p.image}-small.webp`));assert.ok(p.alt&&p.area>0&&p.price>0&&p.tax>=0&&p.fee>=0)}});
check('Todas as páginas principais existem',()=>{for(const route of ['app/page.tsx','app/imoveis/page.tsx','app/imoveis/[id]/page.tsx','app/favoritos/page.tsx','app/contato/page.tsx','app/sobre/page.tsx','app/privacidade/page.tsx','app/not-found.tsx','app/error.tsx','app/loading.tsx'])assert.ok(existsSync(route))});
function luminance(hex){const rgb=hex.match(/\w\w/g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]}
check('Contraste WCAG AA nos pares de texto dos tokens',()=>{for(const [fg,bg] of [['26332e','ffffff'],['59665f','ffffff'],['59665f','f3f5f3'],['173c33','ffffff'],['ffffff','173c33'],['d6e3dc','173c33'],['a12929','ffffff']]){const a=luminance(fg),b=luminance(bg);const ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);assert.ok(ratio>=4.5,`${fg}/${bg}: ${ratio.toFixed(2)}`);console.log(`  Contrast #${fg}/#${bg}: ${ratio.toFixed(2)}:1`)}});
check('CSS inclui intervalos responsivos e redução de movimento',()=>{const css=readFileSync('app/globals.css','utf8');for(const width of ['1200','1023','767','639','359'])assert.ok(css.includes(`max-width:${width}px`));assert.ok(css.includes('prefers-reduced-motion'));assert.ok(css.includes('clamp('));assert.ok(css.includes('color-scheme:light'));assert.ok(!css.includes('prefers-color-scheme: dark'))});
console.log(`${checks} grupos de verificações passaram. Revisão visual e interação no navegador indisponíveis nesta sessão.`);
